services:
  angular-app:
    build: ./angular
    ports:
      - "4200:80"
  json-server:
    image: clue/json-server
    volumes:
      - ./db.json:/data/db.json
    ports:
      - "3000:3000"
  other-app:
    image: nginx
    ports:
      - "8080:8000"
