services:
  angular-app:
    build: .
    ports:
      - "4200:80"
    depends_on:
      - json-server
    networks:
      - app-network
  json-server:
    image: clue/json-server
    volumes:
      - ./db.json:/data/db.json
    ports:
      - "3000:80"
  other-app:
    image: nginx
    ports:
      - "8080:80"
# ⬇️ IMPORTANT : Définir les réseaux ici !
networks:
  app-network:
    driver: bridge
